### PR TITLE
Bug fix for the use and interactions protections

### PR DESCRIPTION
**Pull request by Yuti35**
I've made a little fix in the ProtectionEventHandler class on the playerInteractEvent method.

**What were the issues before :**

1. With the **use** permission denied, it was blocking the item in the main hand, but not in the off hand.
For example, if I denied : **fe.protection.use.minecraft.item_frame** : If I try to use it on a block with the item in my main hand, it's denied, but I put the frame in my off hand, it bypasses it. **This was fixed by getting the item by event.getItemStack()**

2. Still with the **use** permission, it was not blocking the item usage "in the air" (when no interaction with a block) : for example, a bow, enderpearl or the usage of buckets (water, lava). **This was fixed by handling the RightClickItem event and canceling it if the user is not allowed to use the item.**

3. With the **interact** permission, users where able to bypass it if they were sneaking. For example, if I deny interactions with chests, I could still open them by sneaking + right click. **This was fixed by removing the "!event.getEntityPlayer().isSneaking()" part of the condition.**

I tested these fixes on my side, and everything seems to work fine.

If you could accept my PR it would be really good and allow to fix these protection issues on the servers using FE ! Thank you :)

### CODE REVIEW

**Comment by spacebuilder2020** [comment]
This will require some research.  The part about the shift click was added to fix issue #2237 by a former FE developer.

**Comment by Yuti35** [comment]
Ha, I see ! But I'm not sure to understand what what the original issue leading to this.
Does they mean it opens a GUI when it should not = when the interact permission was denied ?
The permission check is not done anymore if the player is sneaking with the fix the developer provided (so the GUI will still pop up I assume).
I just tried on my side, and whith my fix, no GUI are popping when this interact perm is disabled and sneaking (I tried chest, crafting tables furnace, ...) with or without items in hand.

My thought is that the person who reported the bug in the first place may have misconfigured their permissions somehow!
For example : the furnace.
If you deny **fe.protection.interact.minecraft.furnace**, you can still interact with furnace, but the right permisison to deny is **fe.protection.interact.minecraft.furnace.*** (and now, the furnace is well blocked)

**Review by spacebuilder2020 — APPROVED** [review]
Yea, that are my thoughts...  Somehow I don't think the original issue was fixed correctly and the issue itself was unclear.  Well, I am going to test it myself soon and then merge the PR.  It all looks good.

**Comment by Yuti35** [comment]
Thank you ! :)

**Comment by spacebuilder2020** [comment]
No problem, I am glad to see people making PRs again!

**Comment by Yuti35** [comment]
I won't hesitate to do more if I find anything else :)
It's a really usefull mod !

**Comment by spacebuilder2020** [comment]
I am just going to merge it.  I think the risk of there being an issue with the sneaking is low!

**Pull request merged**
