### PR TITLE
1.8.9 update

### PR DESCRIPTION
**Pull request by luacs1998**
Seven months in the making, and I daresay we can stop support for 1.8.0 and start working on 1.8.9.

Up next: 1.10.2 and Sponge!

### CODE REVIEW

**Comment by olee** [comment]
:joy:
It really was time to do that

**Comment by luacs1998** [comment]
@olee ehehehehehe

Well...

**Comment by olee** [comment]
Hm... travis failes.
One of the errors is hibernate annotations (so probably not relevant)

**Comment by luacs1998** [comment]
It is, I can't get hibernate annotations to behave properly on my PC as well :(

The last error is mixin related, so we'll need to fix that before merging.

**Comment by spacebuilder2020** [comment]
I was unable to get the latest version to compile.  I had to downgrade a couple revs back.

**Comment by luacs1998** [comment]
@olee @spacebuilder2020 ready when you are

**Comment by liach** [comment]
Um how about mc 1.9 and 1.10

**Comment by luacs1998** [comment]
Later

**Pull request merged**
