### PR TITLE
Multiworld Updates

### PR DESCRIPTION
**Pull request by DomAmato**
This should fix the multiworld issues,
Sorry the code formatting might be a little off, I used the formatter included before I submitted but the code was formatted for my purposes initially. See issue #2176

### CODE REVIEW

**Comment by luacs1998** [comment]
Great, thanks. However, we're not focusing on 1.8 anymore, so can you make a PR for 1.10 as well?

**Comment by DomAmato** [comment]
this was more to satisfy the problems people were having with the 1.8 branch from the issue I tagged in the pull request but I can see what I can do about updating it for 1.10

**Comment by DomAmato** [comment]
also I realized I didn't handle the refactoring I made for other parts of the project which is why it failed. Ill fix that in a minute

**Comment by luacs1998** [comment]
What refactoring did you do? Like any OSS project I don't like people moving stuff around too much.

**Comment by DomAmato** [comment]
I just moved the logging into the commons for my branch but that wasn't included in the PR and I just forgot to change the import statement. I did it so there weren't two logging classes since it was redundant but like I said it should be back to the original import

**Comment by luacs1998** [comment]
@DomAmato there's too much noise for me to sort out which are real changes and which are reformats.

Can you make an update to 1.10 that **doesn't** have all these refactors?

**Pull request closed without merging**
