### PR TITLE
[WIP] Changes on server vote config

### PR DESCRIPTION
**Pull request by liach**
~~Also upgraded mixin.~~ Needs to review.

### CODE REVIEW

**Comment by luacs1998** [comment]
Remove the mixin changes - I'll do it on my side. Thanks for pointing it out though.

**Comment by luacs1998** [comment]
Have you verified if this works?

**Comment by liach** [comment]
Not tested yet. It is supposed to support these four forms (without count):
`item id`
`mod id:item name`
`item id:meta`
`mod id:item name:meta`

**Comment by luacs1998** [comment]
Please test - also, you may want to resolve merge conflicts.

**Comment by liach** [comment]
Not now...

**Comment by Zethalion** [comment]
I am happy to test. Could give you feedback in a day.

**Pull request closed without merging**
