### PR TITLE
Early port to 1.12

### PR DESCRIPTION
**Pull request by msifd**
Here is seemingly working port to 1.12. I didn't test all features, but it at least works.

Sorry for auto-formatting!

### CODE REVIEW

**Comment by AnrDaemon** [comment]
Is this intended that sonatype repo listed twice?

**Comment by msifd** [comment]
I guess... I didn't add that one.

**Comment by AnrDaemon** [comment]
Did you read your own commits?
https://github.com/ForgeEssentials/ForgeEssentials/pull/2356/commits/ce1fb57c3ccdcd483e16006b9ddbd787cf67f60e#diff-c197962302397baf3a4cc36463dce5eaR9 lines 8 and 18.

**Comment by msifd** [comment]
Yes i do :)
Same lines on main branch: https://github.com/ForgeEssentials/ForgeEssentials/blob/1.12.2/develop/build.gradle

**Comment by spacebuilder2020** [comment]
This is a huge PR with lots and lots of changes, this will take some time to review.

**Comment by olee** [comment]
@msifd it would make checking the changes a lot easier if you could fix the formatting with the specifications of FE - then we wouldn't have to check lots of unchanged code lines.

**Comment by olee** [comment]
Ok I went through all the changes (except build.gradle - that's a whole lot of confusing changes) and it looks pretty good.
So to merge this there're just a few things we need to clear

1. What happened to CommandVanish? What's the reason it was removed?
2. @spacebuilder2020 this merge is going into develop branch it seems - so should we split off the current develop branch to `1.8/develop` and make this a new develop branch? Or think we can have this merge go to a new branch instead?
3. Can someone check if the changes to `build.gradle` are ok like that?
4. Formatting still needs to be fixed in some places

**Comment by spacebuilder2020** [comment]
@olee It is going into the `1.12.2/develop` branch
And yea, formatting is a mess
I plan to check the `build.gradle` file when I get a chance.  There is a ton of noise there.

**Comment by Emilgardis** [comment]
ping @spacebuilder2020 
github has a way to hide whitespace changes with **?w=1**

https://github.com/ForgeEssentials/ForgeEssentials/pull/2356/files?w=1

**Comment by GDnsk** [comment]
How can i install it?

**Comment by spacebuilder2020** [comment]
@msifd I am going to avoid merging at this time as the server crashes at startup when ran with a full forge server.

I tested this with forge version 14.23.2.2624.

A snapshot of the error is below:
`Caused by: java.lang.NoSuchMethodError: net.minecraft.util.text.TextFormatting.getValueByName(Ljava/lang/String;)Lnet/minecraft/util/text/TextFormatting;
	at com.forgeessentials.util.output.ChatOutputHandler.setConfirmationColor(ChatOutputHandler.java:520)
	at com.forgeessentials.util.output.ChatOutputHandler.load(ChatOutputHandler.java:554)
	at com.forgeessentials.core.moduleLauncher.config.ConfigManager.load(ConfigManager.java:95)
	at com.forgeessentials.core.moduleLauncher.config.ConfigManager.registerLoader(ConfigManager.java:75)
	at com.forgeessentials.core.moduleLauncher.config.ConfigManager.registerLoader(ConfigManager.java:65)
	at com.forgeessentials.core.ForgeEssentials.initConfiguration(ForgeEssentials.java:241)
	at com.forgeessentials.core.ForgeEssentials.<init>(ForgeEssentials.java:159)`

**Comment by LoganDark** [comment]
@msifd please finish this, I would really love to get back scripting capabilities! At this time there are no good scripting mods for Minecraft, so I can't add any custom functionality whatsoever

**Comment by spacebuilder2020** [comment]
Closed Due to concerns not being addressed.

**Pull request closed without merging**
